const world_cryosphere = {
    world: {
        name: 'Cryosphere',
        faction: 'Frost Sentinels',
        station: 'Glacier Relay',
        wave: 11,
        color: '#153947',
        accent: '#8be9ff',
        links: [4, 7],
        armor: 0.35,
        shield: 140,
        weapon: 'scatter',
        weapons: 'Cryo scatter / heavy regenerating shields',
        attack: 10,
        defense: 5,
        mix: [0.05, 0.35, 0.4, 0.05, 0.15],
        prices: [38, 9, 29],
        planet: '#78afb8',
    },
    look: {
        biome: 'FROZEN AURORA',
        description: 'Fractured ice moon, polar light ribbons and drifting crystal fields.',
        base: '#05151f',
        cloud: '#266879',
        second: '#295688',
        star: '#d3fbff',
        material: '#98e5f4',
        station: 'Snowflake research dock',
    },
    rules: {
        name: 'Frozen inertia',
        speed: 1.1,
        response: 3,
        drag: 0.055,
        thrust: 340,
        brake: 850,
        projectile: 1.05,
        shield: 0.45,
        gravity: 0.85,
        gun: 0.72,
        magnet: 1,
        energy: 0,
        inertial: true,
        solid: false,
        summary: 'Long drift · faster cannon · slow shield recharge',
        details: [
            'Cold space gives longer coasting and wider turns than Haven. Hold B to brake or countersteer. Click-to-move and guided flight slow down and turn toward the destination automatically.',
            'The cold cannon has a 28% shorter firing interval. Projectiles travel 5% faster.',
            'Shield regeneration runs at only 45% speed. Armor and repair kits are valuable during sustained fights.',
        ],
        prepare: 'Use armor and repair nanites, and start braking before sharp turns.',
    },
    extent: [145000, 110000],
    expedition: {
        radiation: 0,
        required: 0,
        import: 2,
        ship: 'interceptor',
        advice: 'An Interceptor turns quickly on ice. Fit vector stabilizers, cooling and booster reservoirs.',
    },
    music: {
        title: 'A sky made of glass',
        bpm: 60,
        root: 50,
        chords: [
            [0, 3, 7, 14],
            [10, 14, 17, 21],
            [5, 8, 12, 19],
            [7, 10, 14, 21],
        ],
        scale: [0, 2, 3, 7, 9, 10],
        motif: [0, null, 3, null, 4, 2, null, 1],
        cutoff: 2200,
        air: 1.25,
        rhythm: 5,
    },
};
