const world_dustfall = {
    world: {
        name: 'Dustfall',
        faction: 'Dune Marauders',
        station: 'Dustfall Refinery',
        wave: 5,
        color: '#3b2a20',
        accent: '#ffd16e',
        links: [0, 3],
        armor: 0.25,
        shield: 0,
        weapon: 'missile',
        weapons: 'Homing missiles / plated hulls',
        attack: 2,
        defense: 1,
        mix: [0.2, 0.35, 0.25, 0, 0.2],
        prices: [9, 32, 48],
        planet: '#ac764f',
    },
    look: {
        biome: 'DUNE BELT',
        description: 'Cratered desert moon, amber dust and a dense asteroid belt.',
        base: '#170b07',
        cloud: '#92512c',
        second: '#5f3929',
        star: '#ffdfaa',
        material: '#bd9469',
        station: 'Mining refinery',
    },
    rules: {
        name: 'Low-gravity drift',
        speed: 1.15,
        response: 4,
        drag: 0.12,
        thrust: 420,
        brake: 1000,
        projectile: 1.12,
        shield: 1,
        gravity: 0.55,
        gun: 1,
        magnet: 1,
        energy: 0,
        inertial: true,
        solid: true,
        summary: 'Coasting flight · ore cover wears down · double mined cargo',
        details: [
            'Your ship keeps more momentum after WASD is released; its nose turns before thrust changes course. Countersteer or hold B to brake. Click-to-move and guided flight slow down and turn toward the destination automatically.',
            'Hostile fire wears the ore rocks down here. Approach mining fields slowly.',
            'Gravity is 45% weaker. Mining each rock yields two cargo units of ore. Projectiles inherit some launch velocity.',
        ],
        prepare: 'Phase armor cushions rock collisions; the phase drive and brake help navigation.',
    },
    extent: [55000, 38000],
    expedition: {
        radiation: 0,
        required: 0,
        import: 1,
        ship: 'miner',
        advice: 'A Prospector, vector stabilizers and armor handle drifting rocks and heavy cargo.',
    },
    music: {
        title: 'Caravan of dust',
        bpm: 84,
        root: 43,
        chords: [
            [0, 3, 7, 10],
            [5, 8, 12, 15],
            [3, 7, 10, 14],
            [7, 10, 14, 17],
        ],
        scale: [0, 3, 5, 7, 10],
        motif: [0, null, 2, 3, null, 1, 2, null],
        cutoff: 850,
        air: 0.5,
        rhythm: 2,
    },
};
