const world_eclipse = {
    world: {
        name: 'Eclipse',
        faction: 'Void Armada',
        station: 'Last Light Citadel',
        wave: 15,
        color: '#341432',
        accent: '#ff5baf',
        links: [5, 6],
        armor: 0.65,
        shield: 200,
        weapon: 'rail',
        weapons: 'Void railguns / 65% armor + 200 shields',
        attack: 15,
        defense: 6,
        mix: [0.05, 0.4, 0.35, 0.05, 0.15],
        prices: [43, 42, 12],
        planet: '#624476',
    },
    look: {
        biome: 'BLACK CROWN',
        description: 'An eclipsed world, violet accretion rings and broken void monuments.',
        base: '#03040b',
        cloud: '#311641',
        second: '#25203c',
        star: '#d3b6ff',
        material: '#9e72c2',
        station: 'Void citadel',
    },
    rules: {
        name: 'Tidal void',
        speed: 0.9,
        response: 6,
        drag: 0.5,
        thrust: 600,
        brake: 1000,
        projectile: 1,
        shield: 0.7,
        gravity: 2.1,
        gun: 1,
        magnet: 0.72,
        energy: -1.8,
        inertial: false,
        solid: false,
        summary: 'Strong tides · pulse drain · energy-powered turbo',
        details: [
            'Black holes pull at 210% strength. Their cores remain fatal even with shields or during a dash.',
            'Pulse leaks 1.8 energy per second. Each turbo ignition costs 12 energy. Pulse reactors can offset the drain.',
            'Magnet reach is 72% of its usual range and remains always enabled. Shield regeneration is 30% slower.',
        ],
        prepare:
            'Upgrade the pulse reactor, magnet and turbo drive. At least 90% radiation protection is required. Plan local portal jumps across the 240 × 180 km expanse.',
    },
    extent: [240000, 180000],
    expedition: {
        radiation: 5,
        required: 0.9,
        import: 0,
        ship: 'cruiser',
        advice: 'A Cruiser or a heavily lined industrial hull is essential. Bring a reactor and long-range boosters.',
    },
    music: {
        title: 'Between distant tides',
        bpm: 56,
        root: 38,
        chords: [
            [0, 3, 7, 14],
            [8, 12, 15, 19],
            [5, 8, 12, 14],
            [7, 10, 14, 17],
        ],
        scale: [0, 2, 3, 5, 7, 8, 10],
        motif: [0, null, null, 4, null, 2, null, 1],
        cutoff: 700,
        air: 0.8,
        rhythm: 7,
    },
};
