const world_haven = {
    world: {
        name: 'Haven',
        faction: 'Rim Corsairs',
        station: 'Haven Anchorage',
        wave: 1,
        color: '#19324a',
        accent: '#6cf8ec',
        links: [1, 2],
        armor: 0,
        shield: 0,
        weapon: 'plasma',
        weapons: 'Light plasma / unarmored scouts',
        attack: 0,
        defense: 0,
        mix: [0.7, 0, 0.3, 0, 0],
        prices: [12, 26, 36],
        planet: '#397e8c',
    },
    look: {
        biome: 'BLUE SHORES',
        description: 'Ocean planet, soft blue nebulae and orbital traffic.',
        base: '#060e1d',
        cloud: '#285883',
        second: '#236465',
        star: '#d7f4ff',
        material: '#6f99ac',
        station: 'Orbital harbor',
    },
    rules: {
        name: 'Stable orbit',
        speed: 1,
        response: 14,
        drag: 7,
        thrust: 900,
        brake: 1200,
        projectile: 1,
        shield: 1.25,
        gravity: 0.75,
        gun: 1,
        magnet: 1,
        energy: 0.6,
        inertial: false,
        solid: false,
        summary: 'Responsive flight · faster shields · gentle gravity',
        details: [
            'Strong stabilizers stop drift when you release movement.',
            'Shields recharge 25% faster after five safe seconds.',
            'Gravity wells pull at 75% strength. Pulse gains 0.6 energy per second.',
        ],
        prepare: 'A calm world for mining, contracts and shuttle preparation. No radiation; a compact 12 × 10 km map.',
    },
    extent: [12000, 10000],
    expedition: {radiation: 0, required: 0, import: 1, ship: 'scout', advice: 'A scout is enough for sheltered short flights.'},
    music: {
        title: 'Home among the stars',
        bpm: 72,
        root: 48,
        chords: [
            [0, 4, 7, 14],
            [5, 9, 12, 16],
            [9, 12, 16, 19],
            [7, 11, 14, 21],
        ],
        scale: [0, 2, 4, 7, 9],
        motif: [2, null, 4, 3, null, 2, 1, null],
        cutoff: 1600,
        air: 0.9,
        rhythm: 0,
    },
};
