const world_ion_reach = {
    world: {
        name: 'Ion Reach',
        faction: 'Volt Collective',
        station: 'Arc Spire',
        wave: 7,
        color: '#1c2347',
        accent: '#8d9cff',
        links: [1, 2, 4],
        armor: 0.2,
        shield: 65,
        weapon: 'ion',
        weapons: 'Ion bolts drain pulse / regenerative shields',
        attack: 4,
        defense: 3,
        mix: [0.1, 0.25, 0.4, 0.1, 0.15],
        prices: [27, 12, 40],
        planet: '#6574ba',
    },
    look: {
        biome: 'ELECTRIC STORM',
        description: 'Indigo storm planet, electrical arcs and suspended prisms.',
        base: '#080c23',
        cloud: '#3449a0',
        second: '#25517e',
        star: '#b8cfff',
        material: '#779bfa',
        station: 'Gyroscopic array',
    },
    rules: {
        name: 'Conductive storms',
        speed: 1,
        response: 10,
        drag: 3,
        thrust: 700,
        brake: 1100,
        projectile: 1.35,
        shield: 2,
        gravity: 1,
        gun: 1,
        magnet: 1,
        energy: 0,
        inertial: false,
        solid: false,
        summary: 'Fast projectiles · storm charging · shield surges',
        details: [
            'All projectiles travel 35% faster. Shields recharge twice as fast outside combat.',
            'Marked storm fields run a 16-second cycle: calm, three seconds of warning, then four seconds of discharge.',
            'Inside an active discharge, pulse charges at 14 per second while shields lose 12 per second. Charging costs shield strength, leaving you exposed to enemy fire.',
        ],
        prepare: 'Shield capacitors and pulse reactors let you use the storms to your advantage.',
    },
    extent: [42000, 34000],
    expedition: {
        radiation: 0.8,
        required: 0.15,
        import: 0,
        ship: 'courier',
        advice: 'Fit radiation lining and shield capacitors before entering the ion storms.',
    },
    music: {
        title: 'Signals in the rain',
        bpm: 94,
        root: 45,
        chords: [
            [0, 3, 7, 14],
            [8, 12, 15, 19],
            [3, 7, 10, 14],
            [7, 10, 14, 21],
        ],
        scale: [0, 2, 3, 7, 9, 10],
        motif: [0, 3, null, 2, 4, null, 1, 3],
        cutoff: 1900,
        air: 0.85,
        rhythm: 3,
    },
};
