const world_nova_forge = {
    world: {
        name: 'Nova Forge',
        faction: 'Ember Legion',
        station: 'Helios Foundry',
        wave: 13,
        color: '#451e23',
        accent: '#ff9469',
        links: [4, 7],
        armor: 0.6,
        shield: 90,
        weapon: 'missile',
        weapons: 'Seeker volleys / 60% ablative armor',
        attack: 12,
        defense: 5,
        mix: [0.1, 0.35, 0.3, 0.05, 0.2],
        prices: [14, 38, 20],
        planet: '#d47046',
    },
    look: {
        biome: 'SOLAR FOUNDRY',
        description: 'Molten planet, a blazing corona, ember trails and volcanic debris.',
        base: '#1d070b',
        cloud: '#a12b25',
        second: '#7c3919',
        star: '#ffc7a3',
        material: '#ec8661',
        station: 'Solar forge',
    },
    rules: {
        name: 'Reactor heat',
        speed: 1,
        response: 10,
        drag: 3,
        thrust: 720,
        brake: 1100,
        projectile: 1.15,
        shield: 1,
        gravity: 1.1,
        gun: 0.9,
        magnet: 1,
        energy: 0,
        inertial: false,
        solid: false,
        summary: 'Weapon heat · solar flares · reactor cooling',
        details: [
            'Cannon shots add 3 heat and turbo adds heat continuously. At 100 heat weapons lock until heat falls below 55.',
            'Cooling removes 10 heat per second, plus 2 per Pulse-reactor level. The cannon pauses automatically to cool after overheating.',
            'Marked solar fields warn before flaring. Active flares add heat and hurt unshielded hull. Armor reduces this damage.',
        ],
        prepare:
            'Pulse reactors and reactor cooling control heat. Radiation requires at least 80% lining; ordinary shields do not protect the hull from radiation.',
    },
    extent: [115000, 86000],
    expedition: {
        radiation: 3.2,
        required: 0.8,
        import: 1,
        ship: 'gunship',
        advice: 'Use a protected Gunship or Cruiser with radiation lining and reactor cooling.',
    },
    music: {
        title: 'The sun below',
        bpm: 96,
        root: 45,
        chords: [
            [0, 3, 7, 14],
            [8, 12, 15, 19],
            [5, 8, 12, 15],
            [7, 10, 14, 21],
        ],
        scale: [0, 2, 3, 5, 7, 8, 10],
        motif: [0, 4, null, 2, 5, null, 3, 1],
        cutoff: 1250,
        air: 0.65,
        rhythm: 6,
    },
};
