const world_obsidian = {
    world: {
        name: 'Obsidian',
        faction: 'Iron Dominion',
        station: 'Bastion Dock',
        wave: 9,
        color: '#342738',
        accent: '#ed97cf',
        links: [3, 5, 6],
        armor: 0.5,
        shield: 45,
        weapon: 'rail',
        weapons: 'Fast railguns / 50% armor plating',
        attack: 7,
        defense: 4,
        mix: [0.05, 0.5, 0.3, 0, 0.15],
        prices: [34, 27, 15],
        planet: '#67566c',
    },
    look: {
        biome: 'IRON EXPANSE',
        description: 'Fortified industrial planet, steel wreckage and armored outposts.',
        base: '#111017',
        cloud: '#564655',
        second: '#3b424e',
        star: '#e1d2e2',
        material: '#a3a1b5',
        station: 'Armored bastion',
    },
    rules: {
        name: 'Heavy gravity',
        speed: 0.8,
        response: 7,
        drag: 4,
        thrust: 650,
        brake: 1100,
        projectile: 0.82,
        shield: 1,
        gravity: 1.65,
        gun: 1,
        magnet: 1,
        energy: 0,
        inertial: false,
        solid: true,
        summary: 'Heavy handling · planetary pull · reinforced armor',
        details: [
            'Cruise speed is 20% lower and projectiles travel 18% slower.',
            'Black-hole attraction is 65% stronger. The industrial planet also creates a gentle orbital pull. Click-to-move compensates while flying.',
            'Ore rocks provide solid cover. Each phase-armor level blocks 15% incoming damage here instead of 12%.',
        ],
        prepare: 'Upgrade Slipstream and Phase armor. Gravity-rated industrial hulls resist the pull. Fit at least 30% radiation protection.',
    },
    extent: [95000, 70000],
    expedition: {
        radiation: 1.4,
        required: 0.3,
        import: 0,
        ship: 'gunship',
        advice: 'A Gunship has gravity-rated engines, armor and built-in radiation protection.',
    },
    music: {
        title: 'Silent machinery',
        bpm: 64,
        root: 36,
        chords: [
            [0, 3, 7, 14],
            [5, 8, 12, 15],
            [3, 7, 10, 17],
            [7, 10, 14, 17],
        ],
        scale: [0, 3, 5, 7, 10],
        motif: [0, null, null, 2, null, 1, 3, null],
        cutoff: 640,
        air: 0.4,
        rhythm: 4,
    },
};
