const world_verdant = {
    world: {
        name: 'Verdant',
        faction: 'Thorn Swarm',
        station: 'Canopy Exchange',
        wave: 3,
        color: '#123a30',
        accent: '#9dff9b',
        links: [0, 3],
        armor: 0.12,
        shield: 0,
        weapon: 'scatter',
        weapons: 'Scatter cannons / organic armor',
        attack: 1,
        defense: 1,
        mix: [0.2, 0.15, 0.35, 0.3, 0],
        prices: [22, 14, 45],
        planet: '#39875e',
    },
    look: {
        biome: 'LIVING VEIL',
        description: 'Emerald gas giant, luminous spores and organic structures.',
        base: '#05120e',
        cloud: '#126b46',
        second: '#3d7b4b',
        star: '#c6ffc4',
        material: '#83c386',
        station: 'Living canopy',
    },
    rules: {
        name: 'Living currents',
        speed: 0.96,
        response: 8,
        drag: 2,
        thrust: 650,
        brake: 1100,
        projectile: 0.95,
        shield: 1,
        gravity: 1,
        gun: 1,
        magnet: 1.1,
        energy: 0.8,
        inertial: false,
        solid: false,
        summary: 'Moving currents · organic repair · stronger magnet',
        details: [
            'Spatial nebula currents push ships, projectiles, ore and loose artifacts. Their direction changes gradually; mining markers follow the drifting ore.',
            'The living cloud repairs 0.4 hull per second outside combat after five safe seconds.',
            'Magnet reach is 10% larger. Hold B to stabilize against the current. Click-to-move compensates while flying.',
        ],
        prepare: 'Slipstream and repair nanites help long flights through the currents.',
    },
    extent: [30000, 24000],
    expedition: {radiation: 0, required: 0, import: 2, ship: 'courier', advice: 'A Courier and vector stabilizers compensate for the living currents.'},
    music: {
        title: 'The breathing nebula',
        bpm: 78,
        root: 50,
        chords: [
            [0, 3, 7, 14],
            [5, 9, 12, 14],
            [3, 7, 10, 17],
            [7, 10, 14, 19],
        ],
        scale: [0, 2, 3, 5, 7, 9, 10],
        motif: [0, 2, null, 4, 5, null, 3, 1],
        cutoff: 1250,
        air: 1.1,
        rhythm: 1,
    },
};
